int cv_face_init_license_config(void) { return 0; }
int cv_face_destroy_tracker(void) { return 0; }
int cv_face_create_tracker(int* handle) { *handle = 0x13371337; return 0; }
int __appProtect_cv_face_create_tracker_start(void) { return 0; }
int __appProtect_cv_face_create_tracker_fill(void) { return 0; }
int __appProtect_cv_face_create_tracker_end(void) { return 0; }
int cv_face_reset_tracker(void) { return 0; }
int cv_face_release_tracker_result(void) { return 0; }
int cv_face_track_set_detect_face_cnt_limit(void) { return 0; }
int cv_face_track_set_detect_interval(void) { return 0; }
int cv_face_track_set_alignment_threshold(void) { return 0; }
int cv_face_track_info(void) { return 0; }
int cv_face_track(void) { return 0; }
int cv_face_frame_select_in_infrared(void) { return 0; }
int cv_face_destroy_detector(void) { return 0; }
int cv_face_create_detector(void) { return 0; }
int __appProtect_cv_face_create_detector_start(void) { return 0; }
int __appProtect_cv_face_create_detector_fill(void) { return 0; }
int __appProtect_cv_face_create_detector_end(void) { return 0; }
int cv_face_detect_get_threshold(void) { return 0; }
int cv_face_detect_set_threshold(void) { return 0; }
int cv_face_rect_align21p(void) { return 0; }
int cv_face_get_face_pose(void) { return 0; }
int cv_face_detect(void) { return 0; }
int cv_face_release_detector_result(void) { return 0; }
int cv_face_detector_info(void) { return 0; }
int cv_face_open_log(void) { return 0; }
int cv_face_algorithm_info(void) { return 0; }
int cv_face_get_version(void) { return 0; }
int cv_face_destroy_attribute_detector(void) { return 0; }
int cv_face_create_attribute_detector(void) { return 0; }
int __appProtect_cv_face_create_attribute_detector_start(void) { return 0; }
int __appProtect_cv_face_create_attribute_detector_fill(void) { return 0; }
int __appProtect_cv_face_create_attribute_detector_end(void) { return 0; }
int cv_face_attribute_detector_detect(void) { return 0; }
